In [11]:
import numpy as np
students = np.random.randint(50, 101, size=(50,5))
print(students)

[[ 83  55  82 100  80]
 [ 61  91  99  58  69]
 [ 91  82  93  70  70]
 [ 64  75  90  75  71]
 [ 82  99  81  90  91]
 [ 58  93  99  64  83]
 [ 92  86  89  62  76]
 [ 68  89  60  52  94]
 [ 57  57  91  89  95]
 [ 67 100  62  55  56]
 [ 52  55  65 100  99]
 [ 95  91  63  86  50]
 [ 81  99  63  62  68]
 [ 93  92  66  54  80]
 [ 62  77  72  60  64]
 [ 63  84  81  67  66]
 [ 56  95  80  86  90]
 [ 88  73  64  87  73]
 [ 66  87  77  73  98]
 [ 68  53  93  63  65]
 [ 65  52  94  57  70]
 [ 66  86  89  68  93]
 [ 93  55  55  51  72]
 [ 55  67  70  84  87]
 [ 95  61  94  64  71]
 [ 96  98  91  69  79]
 [ 72  71  55  82  86]
 [ 80  59  79  82  81]
 [ 81  60  52  82  92]
 [ 99  81  66  88  73]
 [ 54  81  53  55  82]
 [ 96  99  85  87  91]
 [ 85  69  77  52  58]
 [ 64  90 100  73  92]
 [ 61  80  73  77 100]
 [ 67  67  84  68  83]
 [ 56  94  88  83  63]
 [ 76  74  53  98  99]
 [ 70  77  61  76  79]
 [ 59  83  50  68  84]
 [ 68  90  92  66  60]
 [ 62  79  97  56  80]
 [ 55  90  51  96  94]
 [ 91  79  

In [9]:
students[0,0]
students[:1,:]
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[57, 71, 52, 79, 60],
       [72, 97, 83, 73, 61],
       [76, 75, 85, 53, 90],
       [91, 84, 85, 84, 67],
       [52, 97, 65, 86, 61]])

In [13]:
students[:,0]   #第一科所有的分數
students[:,-1]   #最後一科所有的分數

array([ 80,  69,  70,  71,  91,  83,  76,  94,  95,  56,  99,  50,  68,
        80,  64,  66,  90,  73,  98,  65,  70,  93,  72,  87,  71,  79,
        86,  81,  92,  73,  82,  91,  58,  92, 100,  83,  63,  99,  79,
        84,  60,  80,  94,  60,  69,  94,  61,  65,  94,  89])

In [16]:
np.sum(students[:1])  #第一個學生的總分
np.sum(students[:2], axis=1)  #前2個學生的總分
np.sum(students, axis=1)  #全班每位學生的總分
np.mean(students, axis=0)  #每一科全班的平均
np.median(students, axis=0)  #每一科全班的中位數

array([68. , 80.5, 78. , 68.5, 80. ])